
name: Build into Executables And Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  BuildAndUploadToReleaseAssets:
    runs-on: windows-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.11

        - name: Install Requirements
          run: pip install -r requirements.txt
        
        - name: Build with PyInstaller
          run: pyinstaller --clean main.spec --distpath "./Myth Mod Manager"
        
        - name: Zip Myth Mod Manager
          uses: vimtor/action-zip@v1
          with:
            files: "Myth Mod Manager"
            recursive: false
            dest: Myth-Mod-Manager.zip

        - name: Upload Myth Mod Manager to Latest Release Assets
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: Myth-Mod-Manager.zip